### ISSUE TITLE
print "'{}' is not a feature of the Titanic data. Did you spell something wrong?".format(key)

### ISSUE THREAD

**Issue by 43x79** [rahulravindran0108/Titanic-Survival-Exploraton#1]
I'm not sure why this error appears when I try to import visuals 
![image](https://user-images.githubusercontent.com/30804900/29045094-3b37e882-7b90-11e7-8436-ebe2ce8d89b6.png)

**Comment by rahulravindran0108** [comment]
The ipython notebook is for python2 and you are running python3 (Thats what it seems like from the screenshot). Hence, the err on print statement as in python3 its `print()`

**Comment by das-saikat** [comment]
Following lines need to be changed to make it compatible with python 3
print ("'{}' is not a feature of the Titanic data. Did you spell something wrong?".format(key))

print ("'{}' has too many unique categories to display! Try a different feature.".format(key))

print ("Passengers with missing '{}' values: {} ({} survived, {} did not survive)".format( \
              key, len(nan_outcomes), sum(nan_outcomes == 1), sum(nan_outcomes == 0)))

**Comment by rahulravindran0108** [comment]
@43x79 ^ the above comment should resolve your issue, if you wish to change it on the repo, send in a PR that imports the print function from future in the case of py2

**Comment by rahulravindran0108** [comment]
@43x79 It should be solved now.
